language: c

#######################################################################################


os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  - chmod +x build
  - export BUILDING_ON_CI=y

#######################################################################################


script:  
- ./build -b
